services:
  - type: web
    name: proposal-analyzer
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    env:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
      - key: OPENAI_API_KEY
        sync: false  # This will need to be set manually in the Render dashboard 