services:
  - type: web
    name: proposal-analyzer
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --timeout 300 --workers 1 --worker-class sync --max-requests 100 --bind 0.0.0.0:$PORT app:app
    plan: free
    env:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: HOST
        value: 0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # This will need to be set manually in the Render dashboard 