services:
  - type: web
    name: proposal-analyzer
    env: python
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --timeout 600 --keep-alive 2 --max-requests 1000 --max-requests-jitter 50 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
      - key: OPENAI_API_KEY
        sync: false # Set this in the Render dashboard
      - key: FLASK_SECRET_KEY
        generateValue: true # Let Render generate a secret key 