services:
  - type: web
    name: proposal-analyzer
    env: python
    pythonVersion: "3.9"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"
      - key: FLASK_APP
        value: "app.py"
      - key: FLASK_ENV
        value: "production"
      - key: openai-key
        sync: false # Set this in the Render dashboard
      - key: FLASK_SECRET_KEY
        generateValue: true # Let Render generate a secret key 